server:
  port: 6000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenshaoying/spring-cloud-demo/
          searchPaths:
          username:
          password: